### ISSUE TITLE
缺乏"wechat-dat2picture/asset"文件夹

### ISSUE THREAD

**Issue by Art-Man** [PearceDuan/wechat-dat2picture#1]
缺乏"wechat-dat2picture/asset"文件夹，方便传一下么，3Q

**Comment by PearceDuan** [comment]
> 缺乏"wechat-dat2picture/asset"文件夹，方便传一下么，3Q

你是指[这个](https://github.com/PearceDuan/wechat-dat2picture/tree/main/sample)吗

**Comment by PearceDuan** [comment]
> > 缺乏"wechat-dat2picture/asset"文件夹，方便传一下么，3Q
> 
> 你是指[这个](https://github.com/PearceDuan/wechat-dat2picture/tree/main/sample)吗

我看了下代码，你说的asset是编译自动生成的，你可以 `make linux` or `make windows` or `make prepare` 生成。
